/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { Float, useGLTF } from '@react-three/drei'

const Island = (props) => {
  const { nodes, materials } = useGLTF('models/base_basic_shaded.glb')
  return (
    <group {...props} dispose={null}>
      <Float floatIntensity={0.5} speed={2} rotationIntensity={1.2} floatingRange={[0, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.model.geometry}
          material={materials.CustomMaterial}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </Float>
    </group>
  )
}


useGLTF.preload('models/base_basic_shaded.glb')

export default Island