/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: xenadus (https://sketchfab.com/xenadus)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/react-logo-circle-540ff21ac0f54a038df6f634c7cce726
Title: React logo circle
*/

import React, { useRef } from 'react'
import { Float, useGLTF } from '@react-three/drei'

const ReactLogo = (props) =>{
  const { nodes, materials } = useGLTF('/models/react_logo_circle.glb')
  return (
    <Float
      floatIntensity={2} // Sets the intensity of the floating animation (default: 1)
      speed={2} // Sets the speed of the floating animation (default: 1)
      rotationIntensity={0.25} // Sets the rotation intensity while floating (default: 1)
      floatingRange={[0, 1]} // Sets the vertical floating range (default: [-0.1, 0.1])
    >
      
      <group rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.3} {...props}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.015}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['React-Logo_Material002_0'].geometry}
            material={materials['Material.002']}
            position={[0, 7.935, 0]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[39.166, 39.166, 52.734]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Backdrop_Material001_0.geometry}
            material={materials['Material.001']}
            position={[-17.091, 7.935, 0]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[247.854, 247.854, 52.734]}
          />
        </group>
      </group>
    </Float>
  )
}

useGLTF.preload('/models/react_logo_circle.glb')

export default ReactLogo