import { Float, useGLTF } from '@react-three/drei'
import { useRef, useLayoutEffect } from "react"
import gsap from "gsap"

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

const Target = (props) => {
  const { nodes, materials } = useGLTF('/models/Speakers_Shaded.glb')
  return (
    <group {...props} dispose={null}>
      <Float floatIntensity={0.2} speed={2} rotationIntensity={0.9} floatingRange={[0, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.model.geometry}
          material={materials.CustomMaterial}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </Float>
    </group>
  )
}

useGLTF.preload('/models/Speakers_Shaded.glb')

export default Target